export const ADD_PRODUCT = "ADD_PRODUCT";
export const SET_PRODUCTS = "SET_PRODUCTS";

export const SET_PROVINCES = "SET_PROVINCES";

export const SET_CUSTOMERS = "SET_CUSTOMERS";
export const SEARCH_CUSTOMERS = "SEARCH_CUSTOMERS";

export const ADD_INVOICE = "ADD_INVOICE";
export const SET_INVOICES = "SET_INVOICES";

export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

export const SHOW_MESSAGE = "SHOW_MESSAGE";

// Add Invoice Form
export const INVOICE_FORM_SET_ADD_PRODUCT_DIALOG_OPEN = "INVOICE_FORM_SET_ADD_PRODUCT_DIALOG_OPEN";
export const INVOICE_FORM_SET_CUSTOMER_ID = "INVOICE_FORM_SET_CUSTOMER_ID";
export const INVOICE_FORM_SET_SUGGESTIONS = "INVOICE_FORM_SET_SUGGESTIONS";
export const INVOICE_FORM_SET_SUGGESTION = "INVOICE_FORM_SET_SUGGESTION";

// Sales Report Form
export const SALES_REPORT_FORM_SET_OPEN_DRAWER_STATE = "SALES_REPORT_FORM_SET_OPEN_DRAWER_STATE";
export const SALES_REPORT_FORM_SET_START_DATE = "SALES_REPORT_FORM_SET_START_DATE";
export const SALES_REPORT_FORM_SET_END_DATE = "SALES_REPORT_FORM_SET_END_DATE";
export const SALES_REPORT_FORM_SET_INVOICE_TYPE = "SALES_REPORT_FORM_SET_INVOICE_TYPE";
export const SALES_REPORT_FORM_SET_LOADING_STATE = "SALES_REPORT_FORM_SET_LOADING_STATE";
export const SALES_REPORT_FORM_SET_LIST_PAGE = "SALES_REPORT_FORM_SET_LIST_PAGE";
export const SALES_REPORT_FORM_SET_FINISH_LIST_PAGES = "SALES_REPORT_FORM_SET_FINISH_LIST_PAGES";
export const SALES_REPORT_FORM_SEARCH = "SALES_REPORT_FORM_SEARCH";

export const API = "API";
export const API_START = "API_START";
export const API_END = "API_END";
export const ACCESS_DENIED = "ACCESS_DENIED";
export const API_ERROR = "API_ERROR";
