export const ADD_PRODUCT = "ADD_PRODUCT";
export const SET_PRODUCTS = "SET_PRODUCTS";

export const SET_PROVINCES = "SET_PROVINCES";

export const SET_CUSTOMERS = "SET_CUSTOMERS";
export const SEARCH_CUSTOMERS = "SEARCH_CUSTOMERS";

export const ADD_INVOICE = "ADD_INVOICE";
export const SET_INVOICES = "SET_INVOICES";

export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

export const SHOW_MESSAGE = "SHOW_MESSAGE";

// Add Invoice Form
export const INVOICE_FORM_CLEAR_STATE = "INVOICE_FORM_CLEAR_STATE";
export const INVOICE_FORM_SET_ACTIVE_STEP = "INVOICE_FORM_SET_ACTIVE_STEP";
export const INVOICE_FORM_SET_INVOICE_NO = "INVOICE_FORM_SET_INVOICE_NO";
export const INVOICE_FORM_SET_ADD_PRODUCT_DIALOG_OPEN = "INVOICE_FORM_SET_ADD_PRODUCT_DIALOG_OPEN";
export const INVOICE_FORM_SET_CUSTOMER_ID = "INVOICE_FORM_SET_CUSTOMER_ID";
export const INVOICE_FORM_SET_SUGGESTIONS = "INVOICE_FORM_SET_SUGGESTIONS";
export const INVOICE_FORM_SET_SUGGESTION = "INVOICE_FORM_SET_SUGGESTION";
export const INVOICE_FORM_ADD_NEW_PRODUCT_TO_INVOICE = "INVOICE_FORM_ADD_NEW_PRODUCT_TO_INVOICE";
export const INVOICE_FORM_SET_NEW_PRODUCT = "INVOICE_FORM_SET_NEW_PRODUCT";
export const INVOICE_FORM_REMOVE_PRODUCT_FROM_INVOICE_BY_ID = "INVOICE_FORM_REMOVE_PRODUCT_FROM_INVOICE_BY_ID";
export const INVOICE_FORM_SET_INVOICE_PRODUCT_COUNT = "INVOICE_FORM_SET_INVOICE_PRODUCT_COUNT";
export const INVOICE_FORM_SET_PROVINCE_ID = "INVOICE_FORM_SET_PROVINCE_ID";
export const INVOICE_FORM_SET_CITY_ID = "INVOICE_FORM_SET_CITY_ID";
export const INVOICE_FORM_SET_MAIL_TYPE = "INVOICE_FORM_SET_MAIL_TYPE";
export const INVOICE_FORM_SET_DELIVER_AFTER = "INVOICE_FORM_SET_DELIVER_AFTER";
export const INVOICE_FORM_SET_DELIVER_AFTER_TIME_UNIT = "INVOICE_FORM_SET_DELIVER_AFTER_TIME_UNIT";


// Sales Report Form
export const SALES_REPORT_FORM_SET_OPEN_DRAWER_STATE = "SALES_REPORT_FORM_SET_OPEN_DRAWER_STATE";
export const SALES_REPORT_FORM_SET_START_DATE = "SALES_REPORT_FORM_SET_START_DATE";
export const SALES_REPORT_FORM_SET_END_DATE = "SALES_REPORT_FORM_SET_END_DATE";
export const SALES_REPORT_FORM_SET_INVOICE_TYPE = "SALES_REPORT_FORM_SET_INVOICE_TYPE";
export const SALES_REPORT_FORM_SET_LOADING_STATE = "SALES_REPORT_FORM_SET_LOADING_STATE";
export const SALES_REPORT_FORM_SET_LIST_PAGE = "SALES_REPORT_FORM_SET_LIST_PAGE";
export const SALES_REPORT_FORM_SET_FINISH_LIST_PAGES = "SALES_REPORT_FORM_SET_FINISH_LIST_PAGES";
export const SALES_REPORT_FORM_SEARCH = "SALES_REPORT_FORM_SEARCH";

// Add Product Dialog
export const ADD_PRODUCT_DIALOG_SET_FORM_FIELDS = "ADD_PRODUCT_DIALOG_SET_FORM_FIELDS";
export const ADD_PRODUCT_DIALOG_CLEAR_STATE = "ADD_PRODUCT_DIALOG_CLEAR_STATE";
export const ADD_PRODUCT_DIALOG_SET_LOADING_STATUS = "ADD_PRODUCT_DIALOG_SET_LOADING_STATUS";

export const API = "API";
export const API_START = "API_START";
export const API_END = "API_END";
export const ACCESS_DENIED = "ACCESS_DENIED";
export const API_ERROR = "API_ERROR";
